name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Verify package.json exists
        run: |
          if [ ! -f package.json ]; then
            echo "Error: package.json not found!"
            exit 1
          fi

      - name: Install dependencies
        run: |
          npm install || { echo "npm install failed"; exit 1; }

      - name: Build the app
        run: |
          npm run build || { echo "Build failed"; exit 1; }

      - name: Run tests
        run: |
          npm test || { echo "Tests failed"; exit 1; }



 


