name: Node.js Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Upload test results (if needed)
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path: test-results/


